# MIT License

# Copyright (c) 2024 arfy slowy - DeRuneLabs

name: testing jane workflow linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: installattion golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: build jane
        run: |
          sudo apt-get install build-essential
          sudo apt-get install make
          cd src
          make all
