# MIT License

# Copyright (c) 2024 arfy slowy - DeRuneLabs

name: testing jane workflow windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: installattion golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: build jane
        run: jn_scripts/build.bat
