name: golangci

on: [push, pull_request]
permission:
  contents: read

jobs:
  golangci:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-linting
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
